SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM LOCATIONS;
SELECT * FROM JOBS;
-- 테이블에서 특정 컬럼만 조회하고 싶을 때 : 컬럼명을 ,를 사용하여 나열
SELECT EMPLOYEE_ID, FIRST_NAME, PHONE_NUMBER FROM EMPLOYEES;
-- 문자와 날짜는 좌측정렬, 숫자는 우측에 정렬된다
SELECT FIRST_NAME, HIRE_DATE, SALARY, COMMISSION_PCT FROM EMPLOYEES;
-- 숫자 컬럼은 연산(* / + -)이 가능
SELECT FIRST_NAME, SALARY, SALARY+SALARY*0.1 FROM EMPLOYEES;
SELECT *FROM EMPLOYEES;
SELECT FIRST_NAME, HIRE_DATE, SALARY, COMMISSION_PCT FROM EMPLOYEES;
SELECT * FROM EMPLOYEES;
SELECT * FROM DEPARTMENTS;
SELECT * FROM EMPLOYEES;
--컬럼 앨리어스 : 원하는 컬럼명으로 컬럼의 이름을 바꿔서 내용을 출력(AS는 생략이 가능)
SELECT FIRST_NAME AS 이름, SALARY 급여, SALARY+SALARY*0.1 AS "최종 급여" FROM EMPLOYEES;
--문자열 붙이기 || - 오라클만의 기능임
SELECT FIRST_NAME||'님의 급여는 '||SALARY||' 입니다.' AS SALARY FROM EMPLOYEES;
--홑따옴표는 예약어이므로 문자열 안에서 사용시 2개를 써야 홑따옴표로 인식이 된다

--DISTINCT : 중복 제거
SELECT DISTINCT DEPARTMENT_ID FROM EMPLOYEES;
SELECT DISTINCT FIRST_NAME, DEPARTMENT_ID FROM EMPLOYEES; --조회된 데이터 기준으로 중복을 제거함
--ROWID :  데이터의 주소, ROWNUM :  데이터가 조회된 순서(쿼리가 조회한 행 번호)
SELECT EMPLOYEE_ID, FIRST_NAME, ROWID, ROWNUM FROM EMPLOYEES;