--숫자함수
--Round : 반올림(두번째 매개변수 0이 정수 일의자리수, 음수로 가면 십의자리수, 양수로 가면 소수점 아래)
SELECT ROUND(45.923,2), ROUND(45.923,0), ROUND(45.923,-1) FROM DUAL;

--TRUNC : 절삭
SELECT TRUNC(45.923,2), TRUNC(45.923,0), TRUNC(45.923,-1) FROM DUAL;

--ABS: 절대값, CEIL: 올림, FLOOR: 내림, MOD 나머지
SELECT ABS(-3), CEIL(3.14), FLOOR(3.14), MOD(5,2) FROM DUAL;

--날짜함수
SELECT SYSDATE FROM DUAL;
SELECT SYSTIMESTAMP FROM DUAL;
--날짜는 연산가능
SELECT SYSDATE+1, SYSDATE-1 FROM DUAL;
SELECT SYSDATE - HIRE_DATE FROM EMPLOYEES;
SELECT FLOOR((SYSDATE - HIRE_DATE)/365) FROM EMPLOYEES;

--날짜반올림, 절삭 ROUND, TRUNC : 날짜의 경우에 매개변수로 YEAR, MONTH를 넣을 수 있다
SELECT SYSDATE, ROUND(SYSDATE), TRUNC(SYSDATE) FROM EMPLOYEES;
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;
SELECT TRUNC(SYSDATE, 'MONTH') FROM DUAL;

