--집합연산자
--집합연산자 사용시 두 집합의 컬럼 개수가 일치해야 한다.
--집합연산자는 여러 개 중복해서 사용이 가능하다.

--UNION(결과가 중복되지 않는 합집합)
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
UNION
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--UNION ALL(결과가 중복되는 합집합)
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
UNION ALL
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--INTERSECT(교집합)
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%'
INTERSECT
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20;

--MINUS(차집합)
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE DEPARTMENT_ID = 20
MINUS
SELECT FIRST_NAME, HIRE_DATE FROM EMPLOYEES WHERE HIRE_DATE LIKE '04%';
---------------------------------------------------------------------
SELECT 'PARK', 200 FROM DUAL
UNION ALL
SELECT 'KIM', 300 FROM DUAL
UNION ALL
SELECT 'CHOI', 400 FROM DUAL;


----------------------------------------------------------------------
--분석함수(시험에 자주 나옴)
SELECT FIRST_NAME, 
    SALARY,
    RANK() OVER (ORDER BY SALARY DESC) AS 중복등수,
    DENSE_RANK() OVER (ORDER BY SALARY DESC) AS 중복없는등수,
    ROW_NUMBER() OVER (ORDER BY SALARY DESC) AS 일련번호,
    ROWNUM --ROWNUM(DB저장기준 열번호) 과 ROW_NUMBER()(해당 쿼리문에서의 열번호) 서로 다름 주의
FROM EMPLOYEES;

