--제약 조건: 컬럼에 원하는 형식의 데이터만 입력할 수 있도록 한다.
--primary key : 고유키, 중복 및 NULL 불가, 테이블에서 단 한개의 컬럼만 PK임
--UNIQUE : 중복 불가, NULL값은 허용
--NOT NULL : NULL 입력 불가
--FOREIGN KEY: 참조하는 테이블의 PK 혹은 NULL값만 입력 가능
--CHECK : 컬럼에 들어가는 값에 대한 제한

--명령문이나 마우스로 확인 가능
SELECT * FROM USER_CONSTRAINTS;

--열 레벨에서의 제약 조건
CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2) CONSTRAINT DEPTS_DEPT_NO_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(30) CONSTRAINT DEPTS_DEPT_NAME NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, --값이 들어가지 않을 때 자동으로 넣어주는 값
    DEPT_PHONE VARCHAR2(30) CONSTRAINT DEPTS_DEPT_PHONE UNIQUE,
    DEPT_GENDER CHAR(1) CONSTRAINT DEPTS_DEPT_GENDER CHECK(DEPT_GENDER IN ('M', 'F')),
    LOCA_ID NUMBER(4) CONSTRAINT DEPTS_LOCA_ID_KF REFERENCES LOCATIONS(LOCATION_ID)
);
DROP TABLE DEPTS;
--CONSTRAINT 는 생략가능
CREATE TABLE DEPTS(
    DEPT_NO NUMBER(2) PRIMARY KEY,
    DEPT_NAME VARCHAR2(30) NOT NULL,
    DEPT_DATE DATE DEFAULT SYSDATE, --값이 들어가지 않을 때 자동으로 넣어주는 값
    DEPT_PHONE VARCHAR2(30)  UNIQUE,
    DEPT_GENDER CHAR(1) CHECK(DEPT_GENDER IN ('M', 'F')),
    LOCA_ID NUMBER(4) REFERENCES LOCATIONS(LOCATION_ID)
);
DESC DEPTS;
INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES(100, NULL, '010.......', 'F', 1700);
INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES(1, 'HONG', SYSDATE, '010....', 'X', 1700);
INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES(1, 'HONG', '010....', 'F', 100);
INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES(2, 'HONG', '010....', 'F', 1700);
INSERT INTO DEPTS(DEPT_NO, DEPT_NAME, DEPT_PHONE, DEPT_GENDER, LOCA_ID)
VALUES(1, 'HONG', '010....', 'F', 1700);

--개체무결성 : 기본키에 NULL이 들어갈 수 없고 중복이 불가
--참조무결성 : PK가 아닌 값이 FK의 값으로 들어갈 수 없음
-- 도메인 무결성 : CHECK나 UNIQUE제약을 위배할 수 없음
